refactor local solutions
- extract a (an improvable) new function map_local_basis() out of
  fundamental_matrix_regular(), put it in local_solutions.py;

- move the contents of recurrence.py to local_solutions.py;

- move LogSeriesInitialValues there as well.

Note: before doing

    @@ -615,10 +481,8 @@ def series_sum_regular(Intervals, dop, bwrec, ini, pt, tgt_error,
             sage: logger = logging.getLogger('ore_algebra.analytic.naive_sum')
             sage: logger.setLevel(logging.INFO) # TBI
             sage: dop.numerical_transition_matrix([0,1/10000000])
    -        INFO:ore_algebra.analytic.naive_sum:solution z^(0+0)·log(z)^0/0! + ···
    -        ...
    +        INFO:ore_algebra.analytic.naive_sum:...

I got the following strange error (apparently due to the "·" character,
but which I am unable to reproduce independently):

    sage: dop.numerical_transition_matrix([0,1/10000000]) ## line 483 ##
    INFO:ore_algebra.analytic.naive_sum:initial precision = 69 bits
    INFO:ore_algebra.analytic.naive_sum:summed 50 terms, global tail bound = [1.85869684e-19 +/- 3.34e-28]
    INFO:ore_algebra.analytic.naive_sum:initial precision = 69 bits
    INFO:ore_algebra.analytic.naive_sum:summed 1050 terms, global tail bound = [5.64588985e-7008 +/- 4.90e-7017]
    [        [1.0000001000000050 +/- 1.71e-19] [1.0000000000000000e-7000 +/- 7.01e-7018]]
    [        [1.0000001000000050 +/- 1.94e-19] [1.0000000000000000e-6990 +/- 8.78e-7008]]
    doctest:warning
      ...
      File "/home/marc/co/sage/local/lib/python2.7/doctest.py", line 1556, in check_output
        if got == want:
    :
    UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
    doctest:warning
      ...
      File "/home/marc/co/sage/local/lib/python2.7/doctest.py", line 1576, in check_output
        if got == want:
    :
    UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
    doctest:warning
      ...
      File "/home/marc/co/sage/local/lib/python2.7/doctest.py", line 1585, in check_output
        if got == want:
    :
    UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

    **********************************************************************
    Traceback (most recent call last):
      ...
      File "/home/marc/co/sage/local/lib/python2.7/doctest.py", line 289, in _ellipsis_match
        if got.startswith(w):
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 58: ordinal not in range(128)