bounds: fix type mismatch
Probably due to recent changes but not caught by existing tests. Thanks
to Frédéric Chyzak for the test case.

The error this used to yield:

~/docs/code/sage/ore_algebra/ore_algebra/src/ore_algebra/analytic/bounds.py in series0(self, ord)
    406         for num, den_facto in self.fracs:
    407             den = prod((lin**mult for lin, mult in den_facto), Pol.one()) #slow
--> 408             res += num._mul_trunc_(den.inverse_series_trunc(ord), ord)
    409         return res
    410

[...]

TypeError: unsupported operand parent(s) for +: 'Univariate Polynomial
Ring in z over Complex ball field with 53 bits of precision' and
'Univariate Polynomial Ring in z over Real ball field with 53 bits of
precision'

is quite strange as RBF[z] does coerce into CBF[z]; I am not sure what
kind of strange object calling _mul_trunc_() on arguments of different
types resulted in...