bounds: fix corner case of _exp_part_coeff_lbound()
sage: _, t, Dt = ore_algebra.DifferentialOperators()
....: deq = (9*t^2 - 1)*Dt + 18*t
....: deq.numerical_transition_matrix([0,I,1])

used to fail with

_exp_part_coeff_lbound_finite_radius(self)
    416         # n*lb[n] = α·(n-1)·lb[n-1] + num[0]·lb[n-1]
    417         #                     + ··· + num[s-1]·lb[n-s]
--> 418         num, _ = self.integrand.fracs[-1]
    419         alpha = 1/self.integrand.cvrad
    420

IndexError: list index out of range

due to fracs being [] while self.cvrad < ∞.

Thanks to Pierre Lairez for the report.